---
# nomad.yml
name: "GitHub Action Nomad Run"

"on":
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  pull_request:
    branches: ["**"]
  push:
    tags: ["v*"]
    branches:
      - "master"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  SHA: ${{ github.event.pull_request.head.sha || github.event.after }}

jobs:
  # Build job running on Nomad.
  build-job:
    name: "Run Dummy Test"

    runs-on:
      - nomad

    steps:
      - name: "Checkout repository."
        uses: "actions/checkout@v4"

      - name: "Run Command"
        run: hostname