---
# nomad.yml
name: "GitHub Action Nomad Run"

"on":
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  pull_request:
    branches: ["**"]
  push:
    tags: ["v*"]
    branches:
      - "master"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  SHA: ${{ github.event.pull_request.head.sha || github.event.after }}

jobs:
  # Build job running on Nomad.
  build-job:
    name: "Run Dummy Test"

    runs-on:
      - self-hosted
      - nomad
      - acme_arch_amd64
      - acme_class_builder
      - acme_namespace_prod

    strategy:
      max-parallel: 1
      matrix:
        stream:
          - "master"

    env:
      WORKSPACE: ${{ github.workspace }}

    steps:
      - name: "Checkout repository."
        uses: "actions/checkout@v4"

      - name: "Run Command"
        run: "hostname"